### ISSUE TITLE
Competiton next year

### ISSUE THREAD

**Issue by KailinTong** [cyberbotics/wrestling#116]
Dear authors,

thank you very much about orgianizing this competion!
As a big fan of both mixed martial arts and robotcs and autonomous drving, I can't wait to take part in the next competion.
Will you plan to have a competition next year?

Thank you!
Best regards, Kailin

**Comment by omichel** [comment]
We have no plans yet, but the competition is still open and you can enter it to try to defeat the best competitors out there.
