### ISSUE TITLE
No access to the utils library in the online test

### ISSUE THREAD

**Issue by Jean-Eudes-le-retour** [cyberbotics/wrestling#15]
On the try page of the wrestling competition we can only access the robot controller and not the utils folder nor the motion folder. It would be nice if people could directly use them online to help them making functioning controllers.

We would need to change the dockerCompose field in [webots.yml](../blob/main/webots.yml) but then this will break the default controller name fetch in [competition-record-action](https://github.com/cyberbotics/competition-record-action/blob/main/metascript/animation.py#L27) so it might take a bit of work. What do you think?

**Comment by omichel** [comment]
I will hard-code the name of the participant controller to `participant`. I believe this simplifies a lot of things and is clearer for the users. Also, it doesn't limit any use-case I can imagine.
