### ISSUE TITLE
The repository is becoming very large and long to checkout

### ISSUE THREAD

**Issue by omichel** [cyberbotics/wrestling#30]
It might be worth getting rid of the large file history (mainly animations and x3d files) by following this [method](https://stackoverflow.com/a/13102849/810268).

**Comment by Jean-Eudes-le-retour** [comment]
Here are other blog post that could be interesting:

https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/

**Comment by Jean-Eudes-le-retour** [comment]
Or maybe [Git Large File Storage](https://git-lfs.com/) could help, although it might make generating the animations on webots.cloud more complicated

**Comment by omichel** [comment]
I implemented it.
