### ISSUE TITLE
[question] hardware specs limitations?

### ISSUE THREAD

**Issue by angel-ayala** [cyberbotics/wrestling#4]
Hi!
I was reading the document about the competition, and it is unclear about the hardware available to run the codes.
There will be some CPU, RAM, or GPU limitations?

**Comment by omichel** [comment]
Hi, thank you for asking this question. I will add more details about it in the README.

**Comment by omichel** [comment]
All right, I believe [this](https://github.com/cyberbotics/wrestling/blob/main/README.md#runner-machine-configuration) should answer your question. If not please re-open this issue with more requests.
