### ISSUE TITLE
Exiting with error 1

### ISSUE THREAD

**Issue by amirhnourian** [cyberbotics/wrestling#76]
I am encountering following error:
1m 20s
Run cyberbotics/competition-record-action@v[1](https://github.com/cyberbotics/wrestling/actions/runs/4865602384/jobs/8676119600#step:6:1)
Run cp -r /home/olivier/actions-runner/_work/_actions/cyberbotics/competition-record-action/v1/metascript .
GPU detected on runner machine: nvidia-docker version 20.10.21
Cloning participant repository: amirhnourian/WebotsNaoWresteling
Cloning opponent repository: cyberbotics/wrestling-david
Building Webots docker
Building participant docker (Amir Hossein Nourian)
Building opponent docker (David (Python))
Running game in Webots: Amir Hossein Nourian versus David (Python)
Notice: Amir Hossein Nourian lost over David (Python)
participants.json was uploaded.
animation.json was uploaded.
Error: Process completed with exit code 1.

What is the problem? my simulation works well on my machine

**Comment by omichel** [comment]
You should open the ">" next to the "Running game in Webots: Amir Hossein Nourian versus David (Python)" you will see more details on the error. See [here](https://github.com/cyberbotics/wrestling/actions/runs/4865602384/jobs/8676119600). Basically it says:
```
  Traceback (most recent call last):
  File "participant.py", line 28, in <module>
  from utils.border_detection import BorderDetection
  File "/usr/local/webots-project/controllers/participant/../utils/border_detection.py", line 32, in <module>
  import PIL.Image
  ModuleNotFoundError: No module named 'PIL'
```
Which means you should add `Pillow` in your [Dockerfile](https://github.com/cyberbotics/wrestling/blob/main/controllers/Dockerfile#L9-L11) as a new python dependency along with `opencv-python`, `scipy` and `ahrs`.
